load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "hand_tracking_aar",
    calculators = [
        "//mediapipe/graphs/hand_tracking:multi_hand_mobile_calculators",
    ],
)
